spring:
   application:
      name: mycamundamicroservice
      # see at.phactum.tasklist.tools.common.web.SpaNoHandlerFoundExceptionHandler
      spa-default-file: classpath:/static/frontend/index.html
   mvc:
      # see at.phactum.tasklist.tools.common.web.SpaNoHandlerFoundExceptionHandler
      throw-exception-if-no-handler-found: true
   resources:
      # see at.phactum.tasklist.tools.common.web.SpaNoHandlerFoundExceptionHandler
      add-mappings: false
   h2:
      console:
          enabled: true
   datasource:
      url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: sa

servlet:
   context: /
   
camunda:
   bpm:
      admin-user:
         id: admin
         password: admin
      generic-properties:
         properties:
            initializeTelemetry: false
      filter:
         create: All Tasks
      job-execution:
         max-wait: 10000
      webapp:
         index-redirect-enabled: false
         