openapi: 3.0.3
info:
  title: Frontend API
  description: Frontend API for unified tasklist web GUI.
  version: 1.0.0
servers:
  - url: /frontend-api/v1
paths:
  /usertasks/{taskId}:
    get:
      tags:
        - userTasks
      operationId: getUserTaskDetails
      description: details of a certain usertask
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: usertask details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserTaskInstance'
        400:
          description: no or invalid taskId
        404:
          description: no task for the given taskId found
        401:
          description: You are not authorized to access the item
        403:
          description: Accessing the resource you were trying to reach is forbidden
  /usertasks:
    get:
      tags:
        - userTasks
      operationId: getUserTasksDetails
      description: details of a all usertasks
      responses:
        200:
          description: usertask details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserTaskInstance'
        401:
          description: You are not authorized to access the item
        403:
          description: Accessing the resource you were trying to reach is forbidden
components:
  schemas:
    UserTaskInstanceStatus:
      type: string
      enum:
        - ACTIVE
        - SUSPENDED
        - COMPLETED
        - CANCELLED
    UserTaskInstance:
      type: object
      properties:
        id:
          type: string
        formKey:
          type: string
        processInstanceId:
          type: string
        assignee:
          type: string
        tenant:
          type: string
        status:
          $ref: '#/components/schemas/UserTaskInstanceStatus'
        readOnly:
          type: boolean